name: Rust Semver Checks
on:
  workflow_call:
    inputs:
      working-directory:
        description: "Working directory relative to the repository root"
        required: false
        default: "."
        type: string
  workflow_dispatch:
    inputs:
      working-directory:
        description: "Working directory relative to the repository root"
        required: false
        default: "."
        type: string

jobs:
  semver-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Run cargo-semver-checks
        shell: bash
        run: |
          export CARGO_TERM_COLOR=always
          cargo install cargo-semver-checks --locked
          cargo semver-checks check-release
